"""MARIANO Web Core — Workspace Router. Handles dynamic file listing and reading in data/workspace."""
from __future__ import annotations

import os
from pathlib import Path
from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse
from pydantic import BaseModel
from mariano.core.workspace import PathGuard
from mariano.config import get_settings

router = APIRouter(prefix="/api/workspace", tags=["workspace"])


# ── Default workspace content ────────────────────────────────────────────────
_DEFAULT_FOLDERS = {
    "My Research": {
        "README.md": """# My Research

This folder is managed by MARIANO AI.
Here you'll find:
- Research summaries and findings
- Topic deep-dives saved during chat sessions
- Notes compiled from your questions

> MARIANO will automatically save research results here when you ask it to.

---
_Powered by MARIANO AI — your personal intelligence layer._
"""
    },
    "Reports": {
        "README.md": """# Reports

This folder stores structured reports generated by MARIANO AI.
Examples:
- Weekly briefings
- Market analysis reports
- Custom exports from chat sessions

> You can ask MARIANO: \"Save this as a report\" and it will appear here.
"""
    },
    "Notes": {
        "Getting Started.md": """# Welcome to MARIANO Workspace

This is your personal AI-powered storage space.
Think of it as your intelligent file cabinet — organised and always ready.

## What can MARIANO store here?
- Research findings from web searches
- Summaries and notes from your conversations
- Data exports (CSV, JSON, Markdown)
- Generated reports and analysis

## What is NEVER stored here?
- MARIANO's own source code
- System configuration files
- Internal AI model data

## Future: When MARIANO is installed as an app
Your workspace data will live at:
  C:\\Users\\<you>\\AppData\\Local\\MARIANO\\Workspace\\

This keeps your personal data completely separate from the application itself,
just like how other professional software (VS Code, Obsidian) manages user data.

---
Get started by asking MARIANO anything — your results can be saved here!
"""
    },
    "Exports": {
        "README.md": """# Exports

Files exported from MARIANO will appear here.
- CSV sheets from data queries
- JSON data from API calls
- PDF summaries

> This folder is write-only for AI. You can read, copy, or delete files freely.
"""
    },
}


def seed_default_workspace(workspace_dir: Path) -> None:
    """Creates the default folder structure only if workspace is brand new (empty)."""
    existing = [e for e in workspace_dir.iterdir() if not e.name.startswith(".")]
    if existing:
        return  # Already has content — don't overwrite
    
    for folder_name, files in _DEFAULT_FOLDERS.items():
        folder_path = workspace_dir / folder_name
        folder_path.mkdir(parents=True, exist_ok=True)
        for file_name, content in files.items():
            file_path = folder_path / file_name
            if not file_path.exists():
                file_path.write_text(content, encoding="utf-8")


# ── Helpers ──────────────────────────────────────────────────────────────────
def get_workspace_dir() -> Path:
    """Helper to resolve workspace directory path securely."""
    settings = get_settings()
    workspace_dir = settings.mariano_data_dir / "workspace"
    workspace_dir.mkdir(parents=True, exist_ok=True)
    resolved = workspace_dir.resolve()
    seed_default_workspace(resolved)
    return resolved


# ── Routes ───────────────────────────────────────────────────────────────────
@router.get("")
async def get_workspace(
    path: str = Query("", description="Relative path within workspace"),
    project_path: str = Query("", description="Absolute path of active project")
):
    """Lists files and directories inside the specified relative workspace path."""
    if project_path and Path(project_path).is_absolute():
        workspace_dir = Path(project_path).resolve()
        workspace_dir.mkdir(parents=True, exist_ok=True)
    else:
        workspace_dir = get_workspace_dir()
    
    # Resolve target directory securely
    try:
        if path:
            target_dir = (workspace_dir / path).resolve()
        else:
            target_dir = workspace_dir
        
        # Security Guard: Prevent directory traversal outside data/workspace
        if not target_dir.is_relative_to(workspace_dir):
            raise HTTPException(status_code=403, detail="Access denied: outside workspace scope.")
            
        if not target_dir.exists():
            raise HTTPException(status_code=404, detail="Directory not found.")
        if not target_dir.is_dir():
            raise HTTPException(status_code=400, detail="Target path is not a directory.")
            
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Invalid path configuration: {exc}")

    items = []
    try:
        for entry in sorted(target_dir.iterdir(), key=lambda e: (not e.is_dir(), e.name.lower())):
            # Skip hidden files
            if entry.name.startswith("."):
                continue
                
            is_dir = entry.is_dir()
            stat = entry.stat()
            
            # Format relative path with forward slashes for web consistency
            rel_path = str(entry.relative_to(workspace_dir)).replace("\\", "/")
            
            items.append({
                "name": entry.name,
                "is_dir": is_dir,
                "size_bytes": stat.st_size if not is_dir else 0,
                "modified_time": stat.st_mtime,
                "relative_path": rel_path
            })
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to scan directory: {exc}")

    return {
        "current_path": path.replace("\\", "/"),
        "items": items
    }


@router.get("/list-projects")
async def list_projects():
    """Lists all projects/workspaces inside the workspace root folder."""
    workspace_dir = get_workspace_dir()
    try:
        projects = []
        for entry in workspace_dir.iterdir():
            if entry.is_dir() and not entry.name.startswith("."):
                stat = entry.stat()
                projects.append({
                    "name": entry.name,
                    "path": str(entry.resolve()),
                    "modified_time": stat.st_mtime
                })
        # Sort by modified time descending (newest first)
        projects.sort(key=lambda p: p["modified_time"], reverse=True)
        return {"projects": projects}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


class WorkspaceSetRequest(BaseModel):
    project_id: str
    project_path: str | None = None


@router.post("/set")
async def set_active_workspace(req: WorkspaceSetRequest):
    """Sets the active project workspace context, initializes and seeds directories."""
    try:
        settings = get_settings()
        project_id = req.project_id
        project_path = req.project_path
        
        # If project_path is empty or not absolute, resolve to local sandbox
        if not project_path or not Path(project_path).is_absolute():
            proj_dir = (settings.mariano_data_dir / "workspace" / project_id).resolve()
        else:
            proj_dir = Path(project_path).resolve()
            
        # Ensure workspace folder exists
        proj_dir.mkdir(parents=True, exist_ok=True)
        seed_default_workspace(proj_dir)
        
        # Set transient project context in PathGuard
        PathGuard.set_active_project(project_id, project_path=str(proj_dir))
        
        return {
            "status": "success",
            "project_id": project_id,
            "project_path": str(proj_dir),
            "exists": proj_dir.exists()
        }
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


# (file-diff route removed)


@router.get("/file")
async def read_workspace_file_alias(
    path: str = Query(..., description="Relative path of file to read"),
    project_path: str = Query("", description="Absolute path of active project")
):
    """Alias endpoint that matches frontend call convention (/api/workspace/file?path=...)."""
    return await _read_file_content(path, project_path)


@router.get("/read")
async def read_workspace_file(
    file_path: str = Query(..., description="Relative path of file to read"),
    project_path: str = Query("", description="Absolute path of active project")
):
    """Read file content from workspace. (Legacy endpoint kept for compatibility)"""
    return await _read_file_content(file_path, project_path)


async def _read_file_content(file_path: str, project_path: str = "") -> dict:
    """Safely reads content of a text file inside the workspace."""
    if project_path and Path(project_path).is_absolute():
        workspace_dir = Path(project_path).resolve()
    else:
        workspace_dir = get_workspace_dir()
    
    try:
        target_file = (workspace_dir / file_path).resolve()
        
        # Security Guard: Prevent directory traversal outside the workspace scope
        if not target_file.is_relative_to(workspace_dir):
            raise HTTPException(status_code=403, detail="Access denied: outside workspace scope.")
            
        if not target_file.exists():
            raise HTTPException(status_code=404, detail="File not found.")
        if not target_file.is_file():
            raise HTTPException(status_code=400, detail="Target path is not a file.")
            
        # Read text content safely (limit 2MB)
        file_size = target_file.stat().st_size
        if file_size > 2 * 1024 * 1024:
            raise HTTPException(status_code=413, detail="File too large to preview (max 2MB).")
        
        content = target_file.read_text(encoding="utf-8", errors="replace")
        return {"path": file_path, "name": target_file.name, "content": content}
        
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to read file: {exc}")


@router.get("/render/{file_path:path}")
async def render_file_path(file_path: str):
    """Serve files by path parameter to support relative resource loading in iframe."""
    try:
        # Standardize drive letter path capture (e.g., "D/web-test/..." -> "D:/web-test/...")
        if len(file_path) > 2 and file_path[1] == '/' and file_path[0].isalpha():
            file_path = file_path[0] + ":" + file_path[1:]
            
        raw_path = Path(file_path)
        antigravity_path = Path("C:/Users/anshu/.gemini/antigravity").resolve()
        if raw_path.is_absolute() and raw_path.resolve().is_relative_to(antigravity_path):
            resolved_path = raw_path.resolve()
        else:
            resolved_path = PathGuard.secure_path(file_path)
            
        if not resolved_path.is_file():
            raise HTTPException(status_code=400, detail="Path is not a file")
            
        # Determine media type for preview assets to avoid browser MIME type enforcement blocking
        media_type = None
        ext = resolved_path.suffix.lower()
        if ext == ".css":
            media_type = "text/css"
        elif ext in (".js", ".mjs"):
            media_type = "application/javascript"
        elif ext == ".svg":
            media_type = "image/svg+xml"
            
        return FileResponse(resolved_path, media_type=media_type)
    except PermissionError as exc:
        raise HTTPException(status_code=403, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/render")
async def render_file(path: str = Query(..., description="Path of file to render")):
    """Dynamically serve files from workspace or host (if authorized) to allow live rendering in iframe/image previews."""
    try:
        raw_path = Path(path).resolve()
        repo_root = Path(__file__).resolve().parent.parent.parent
        workspace_base = (repo_root / "data" / "workspace").resolve()
        antigravity_path = Path("C:/Users/anshu/.gemini/antigravity").resolve()

        # Allow serving any valid file inside data/workspace or .gemini/antigravity
        if raw_path.is_file():
            if (workspace_base in raw_path.parents or raw_path == workspace_base) or (antigravity_path in raw_path.parents or raw_path == antigravity_path):
                return FileResponse(raw_path)

        resolved_path = PathGuard.secure_path(path)
        if not resolved_path.is_file():
            raise HTTPException(status_code=400, detail="Path is not a file")
        return FileResponse(resolved_path)
    except PermissionError as exc:
        raise HTTPException(status_code=403, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.post("/browse")
async def browse_folder():
    """Triggers a native host folder picker dialog and returns the selected path."""
    import asyncio
    import subprocess
    import sys

    def _browse():
        cmd = [
            sys.executable,
            "-c",
            "import tkinter as tk; from tkinter import filedialog; root=tk.Tk(); root.withdraw(); root.attributes('-topmost', True); print(filedialog.askdirectory(title='Select Project Directory'))"
        ]
        kwargs: dict = {}
        if sys.platform == "win32":
            # CREATE_NO_WINDOW suppresses the console window without triggering
            # WinError 50, which STARTF_USESHOWWINDOW via STARTUPINFO can cause
            # when the server is running as a non-interactive process.
            kwargs["creationflags"] = 0x08000000  # CREATE_NO_WINDOW

        # Run tkinter in its own process to bypass async worker thread affinity check.
        # stdin=DEVNULL is required for PyInstaller frozen contexts where the parent
        # process has no valid stdin handle, which causes WinError 50 otherwise.
        result = subprocess.run(
            cmd,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            **kwargs
        )
        return result.stdout.decode("utf-8").strip()

    try:
        path = await asyncio.to_thread(_browse)
        return {"path": path}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/simulations")
async def list_simulations():
    """List all available simulation files inside mariano/data/simulations."""
    try:
        simulations_dir = Path(__file__).resolve().parent.parent / "data" / "simulations"
        if not simulations_dir.exists():
            return {"simulations": []}
        
        files = []
        for p in simulations_dir.glob("*.json"):
            if p.is_file():
                try:
                    import json
                    data = json.loads(p.read_text(encoding="utf-8"))
                    name = data.get("simulation_name", p.name)
                    date = data.get("date_run", "")
                    meta = data.get("metadata", {})
                except Exception:
                    name = p.name
                    date = ""
                    meta = {}
                
                files.append({
                    "filename": p.name,
                    "name": name,
                    "date": date,
                    "size_bytes": p.stat().st_size,
                    "metadata": meta
                })
        return {"simulations": files}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/simulations/{filename}")
async def get_simulation_detail(filename: str):
    """Read specific simulation data file inside mariano/data/simulations."""
    try:
        simulations_dir = (Path(__file__).resolve().parent.parent / "data" / "simulations").resolve()
        target_file = (simulations_dir / filename).resolve()
        
        if not target_file.is_relative_to(simulations_dir):
            raise HTTPException(status_code=403, detail="Access denied.")
        if not target_file.exists() or not target_file.is_file():
            raise HTTPException(status_code=404, detail="Simulation not found.")
            
        import json
        data = json.loads(target_file.read_text(encoding="utf-8"))
        return data
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


from pydantic import BaseModel

class SimulationRunRequest(BaseModel):
    simulation_name: str
    pipe_diameter_mm: float | None = 50.0
    pipe_length_mm: float | None = 300.0
    wall_thickness_mm: float | None = 10.0
    max_temperature_c: float | None = 700.0
    min_temperature_c: float | None = 200.0
    thermal_conductivity_w_mk: float | None = 25.0
    max_shear_stress_pa: float | None = 4.5
    pitting_rate_mm_year: float | None = 1.25
    electrolyte_conductivity_s_m: float | None = 2.1


@router.post("/simulations/run")
async def run_simulation(req: SimulationRunRequest):
    """
    Simulation runner — Kaggle GPU backend has been removed.
    Returns 503 to notify callers that this feature is no longer available.
    """
    raise HTTPException(
        status_code=503,
        detail="GPU simulation via Kaggle has been removed. Feature unavailable."
    )


@router.delete("/simulations/{filename}")
async def delete_simulation(filename: str):
    """
    Deletes a specific simulation data file inside mariano/data/simulations.
    """
    try:
        simulations_dir = (Path(__file__).resolve().parent.parent / "data" / "simulations").resolve()
        target_file = (simulations_dir / filename).resolve()
        if not target_file.is_relative_to(simulations_dir):
            raise HTTPException(status_code=403, detail="Access denied.")
        if not target_file.exists():
            raise HTTPException(status_code=404, detail="Simulation file not found.")
        
        target_file.unlink()
        return {"status": "success", "message": f"Deleted {filename} successfully."}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))



