import sys
from pathlib import Path
from fpdf import FPDF

class DietPDF(FPDF):
    def header(self):
        # Header banner
        self.set_fill_color(34, 139, 34) # Forest Green
        self.rect(0, 0, 297, 24, 'F')
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, 'HIGH CALORIE DIET & NUTRITION PLAN (3100+ KCAL)', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 9)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by Hekki AI Assistant - Page {self.page_no()}', 0, 0, 'C')

def generate_diet_pdf(output_path):
    pdf = DietPDF(orientation='L', unit='mm', format='A4')
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Title Subheading
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 8, 'Daily Routine & Meal Schedule - Muscle Building & High Energy Focus', 0, 1, 'L')
    pdf.ln(2)

    # Table Header
    headers = ["Time", "Meal / Schedule", "Food Items & Portion", "Protein (g)", "Calories (Kcal)"]
    col_widths = [30, 55, 120, 30, 37]
    
    pdf.set_fill_color(46, 117, 89) # Elegant Dark Teal Green
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 10)
    
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 8, h, 1, 0, 'C', fill=True)
    pdf.ln()

    # Meal Data
    meals = [
        ("07:00 AM", "Wake-up Hydration", "500ml Warm Water + 5 Almonds + 2 Walnuts", "3g", "150 Kcal"),
        ("08:00 AM", "Breakfast", "4 Whole Eggs / Paneer (150g) + 3 Oats Roti + 1 Glass Whole Milk", "35g", "650 Kcal"),
        ("11:00 AM", "Mid-Morning Shake", "High Calorie Shake: 1 Banana, 50g Oats, 2 tbsp Peanut Butter, Milk", "25g", "550 Kcal"),
        ("01:30 PM", "Lunch", "150g Chicken / Paneer + 2 Cup Brown Rice + Dal + Green Salad", "40g", "750 Kcal"),
        ("05:00 PM", "Pre-Workout Snack", "2 Whole Wheat Bread Slices + 2 tbsp Peanut Butter + 1 Apple", "12g", "350 Kcal"),
        ("07:30 PM", "Post-Workout", "1 Scoop Whey / 5 Egg Whites + 1 Banana", "28g", "220 Kcal"),
        ("09:30 PM", "Dinner", "150g Fish / Paneer / Tofu + 2 Chapati + Mixed Veggies + Curd", "35g", "550 Kcal"),
    ]

    pdf.set_font('Helvetica', '', 9.5)
    fill = False
    for row in meals:
        if fill:
            pdf.set_fill_color(240, 248, 240) # Light Green Tint
        else:
            pdf.set_fill_color(255, 255, 255)
            
        pdf.set_text_color(30, 30, 30)
        pdf.cell(col_widths[0], 7.5, row[0], 1, 0, 'C', fill=fill)
        pdf.cell(col_widths[1], 7.5, row[1], 1, 0, 'L', fill=fill)
        pdf.cell(col_widths[2], 7.5, row[2], 1, 0, 'L', fill=fill)
        pdf.cell(col_widths[3], 7.5, row[3], 1, 0, 'C', fill=fill)
        pdf.cell(col_widths[4], 7.5, row[4], 1, 0, 'C', fill=fill)
        pdf.ln()
        fill = not fill

    # Total Summary Footer Row
    pdf.set_font('Helvetica', 'B', 10.5)
    pdf.set_fill_color(220, 235, 220)
    pdf.set_text_color(0, 80, 0)
    pdf.cell(col_widths[0] + col_widths[1] + col_widths[2], 8, "TOTAL DAILY NUTRITION TARGET", 1, 0, 'R', fill=True)
    pdf.cell(col_widths[3], 8, "~178g", 1, 0, 'C', fill=True)
    pdf.cell(col_widths[4], 8, "~3170 KCAL", 1, 0, 'C', fill=True)
    pdf.ln()

    # Save PDF
    out_file = Path(output_path)
    out_file.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(out_file))
    print(f"Successfully created: {out_file.resolve()}")

if __name__ == "__main__":
    generate_diet_pdf("D:/Diet_Plan_Updated.pdf")
    generate_diet_pdf("D:/Diet_Plan.pdf")
